container_image = docker://projectmonai/monai:latest
universe = container

log = job_$(Cluster)_$(Process).log
error = job_$(Cluster)_$(Process).err
output = job_$(Cluster)_$(Process).out

executable = run.sh

should_transfer_files = YES
when_to_transfer_output = ON_EXIT_OR_EVICT
transfer_input_files = ALTS.zip, WORD.zip, run.sh

+WantGPULab = true
+GPUJobLength = "short"
request_gpus = 1
require_gpus = GlobalMemoryMb >= 11000
request_cpus = 10
request_memory = 40GB
request_disk = 30GB

queue