wandb_version: 1

learning_rate:
  desc: null
  value: 0.0001
architecture:
  desc: null
  value: U-Net
dataset:
  desc: null
  value: WORD
epochs:
  desc: null
  value: 100
_wandb:
  desc: null
  value:
    python_version: 3.9.19
    cli_version: 0.17.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1716469465
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.9.19
      5: 0.17.0
      8:
      - 5
      13: darwin-x86_64
